---
name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - id: release-please
        name: Release Please
        uses: google-github-actions/release-please-action@v3
        with:
          release-type: go
          package-name: warden-exporter
          changelog-types: >-
            [
              {"type":"feat","section":"Features","hidden":false},
              {"type":"fix","section":"Bug Fixes","hidden":false},
              {"type":"chore","section":"Miscellaneous","hidden":true}
            ]

      - name: Checkout
        uses: actions/checkout@v3
        if: steps.release-please.outputs.release_created
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v4
        if: steps.release-please.outputs.release_created
        with:
          go-version-file: go.mod

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        if: steps.release-please.outputs.release_created

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        if: steps.release-please.outputs.release_created

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        if: steps.release-please.outputs.release_created
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        if: steps.release-please.outputs.release_created
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:${{ github.sha }}
            ghcr.io/${{ github.repository }}:${{
              steps.release-please.outputs.tag_name }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
